name: 'Run a Wappalyzer scan'
description: 'Run a Wappalyzer scan on an url'
inputs:
  url: 
    description: 'URL ro scan'
    required: true
  output:
    description: 'Path to output file. defaults to wappalyzer.json'
    default: 'wappalyzer.json'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - shell: bash
      run: |
        cd ${{ github.action_path }}
        yarn
        node src/scan ${{ inputs.url }} > ${{ github.workspace }}/${{ inputs.output }}
